-- MySQL Script generated by MySQL Workbench
-- 12 أبر, 2018 EET 05:46:03 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema locatemedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locatemedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locatemedb` DEFAULT CHARACTER SET latin1 ;
USE `locatemedb` ;

-- -----------------------------------------------------
-- Table `locatemedb`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locatemedb`.`countries` (
  `id` INT(11) NOT NULL,
  `int_calling_code` SMALLINT(4) NULL DEFAULT NULL,
  `currency` CHAR(3) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `vat_rate` DECIMAL(4,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `locatemedb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locatemedb`.`address` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `created` TIMESTAMP NULL DEFAULT NULL,
  `updated` TIMESTAMP NULL DEFAULT NULL,
  `countries_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_countries1_idx` (`countries_id` ASC),
  CONSTRAINT `fk_address_countries1`
    FOREIGN KEY (`countries_id`)
    REFERENCES `locatemedb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `locatemedb`.`geocoordinates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locatemedb`.`geocoordinates` (
  `id` INT(11) NOT NULL,
  `latitude` FLOAT(10,6) NULL DEFAULT NULL,
  `longitude` FLOAT(10,6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `locatemedb`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locatemedb`.`companies` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `registration` VARCHAR(64) NULL DEFAULT NULL,
  `www` VARCHAR(128) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `description` BLOB NULL DEFAULT NULL,
  `company_logo` VARCHAR(255) NULL DEFAULT NULL,
  `established` DATE NULL DEFAULT NULL,
  `ratings` DECIMAL(3,2) NULL DEFAULT NULL,
  `created` TIMESTAMP NULL DEFAULT NULL,
  `updated` TIMESTAMP NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT NULL,
  `geocoordinates_id` INT(11) NOT NULL,
  `address_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_companies_geocoordinates_idx` (`geocoordinates_id` ASC),
  INDEX `fk_companies_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_companies_geocoordinates`
    FOREIGN KEY (`geocoordinates_id`)
    REFERENCES `locatemedb`.`geocoordinates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `locatemedb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `locatemedb`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locatemedb`.`states` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `countries_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_states_countries1_idx` (`countries_id` ASC),
  CONSTRAINT `fk_states_countries1`
    FOREIGN KEY (`countries_id`)
    REFERENCES `locatemedb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `locatemedb`.`local_government`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locatemedb`.`local_government` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `states_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_local_government_states1_idx` (`states_id` ASC),
  CONSTRAINT `fk_local_government_states1`
    FOREIGN KEY (`states_id`)
    REFERENCES `locatemedb`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
